In [66]:
import pandas as pd

data = pd.read_csv("titanic.csv")

data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [67]:
data["Age"] = data["Age"].fillna(data["Age"].median())
data["Embarked"] = data["Embarked"].fillna(data["Embarked"].mode()[0])
data["Fare"] = data["Fare"].fillna(data["Fare"].median())

In [68]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [69]:
data["Age"] = data["Age"].astype(int)

In [70]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 83.7+ KB

In [71]:
data = data[[
    "Survived",
    "Pclass",
    "Sex",
    "Age",
    "Fare",
    "Embarked",
    "SibSp",
    "Parch"
]]
data.head()

   Survived  Pclass     Sex  Age     Fare Embarked  SibSp  Parch
0         0       3    male   22   7.2500        S      1      0
1         1       1  female   38  71.2833        C      1      0
2         1       3  female   26   7.9250        S      0      0
3         1       1  female   35  53.1000        S      1      0
4         0       3    male   35   8.0500        S      0      0

In [72]:
data["Sex"] = data["Sex"].map({"male":0,"female":1})

data["Embarked"] = data["Embarked"].map({
    "S":0,
    "C":1,
    "Q":2
})

In [73]:
data.head()

   Survived  Pclass  Sex  Age     Fare  Embarked  SibSp  Parch
0         0       3    0   22   7.2500         0      1      0
1         1       1    1   38  71.2833         1      1      0
2         1       3    1   26   7.9250         0      0      0
3         1       1    1   35  53.1000         0      1      0
4         0       3    0   35   8.0500         0      0      0

In [74]:
data["FamilySize"] = data["SibSp"] + data["Parch"] + 1
data["IsAlone"] = (data["FamilySize"] == 1).astype(int)
data.head()

,Survived,Pclass,Sex,Age,Fare,Embarked,SibSp,Parch,FamilySize,IsAlone
0,0,3,0,22,7.2500,0,1,0,2,0
1,1,1,1,38,71.2833,1,1,0,2,0
2,1,3,1,26,7.9250,0,0,0,1,1
3,1,1,1,35,53.1000,0,1,0,2,0
4,0,3,0,35,8.0500,0,0,0,1,1

In [75]:
X = data[[
    "Pclass",
    "Sex",
    "Age",
    "Fare",
    "Embarked",
    "FamilySize",
    "IsAlone"
]]

y = data["Survived"]

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [77]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=500,
    max_depth=10,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_estimators=500, random_state=42)

In [78]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.8268156424581006

In [82]:
passenger = [[1,1,26,40,0,1,1]] # Pclass, Sex, Age, Fare, Embarked, FamilySize, IsAlone

prediction = model.predict(passenger)

print(prediction)

[1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [83]:
import joblib

joblib.dump(model, "titanic_model.pkl")

['titanic_model.pkl']